### ISSUE TITLE
build instructions for other linux distros

### ISSUE THREAD

**Issue by ExileFox** [NeonCrafter13/Transport-Fever-2-NeonModManager#35]
**Is your feature request related to a problem? Please describe.**
deb, rpm are not universal formats

**Describe the solution you'd like**
build instructions for other linux distros, i.e. Arch, Mint, etc

**Describe alternatives you've considered**
N/A

**Additional context**
Additionally, AppImage builds would be nice to see, but having build instructions is preferable.

**Comment by NeonCrafter13** [comment]
On Mint, you can install the .deb package. But I will add instructions to also run the Program on other Platforms. I will lock into AppImages. Thanks for your recommendations.

**Comment by ExileFox** [comment]
I didn't know mint supported Debian packages

**Comment by NeonCrafter13** [comment]
Appimages will not be added

**Comment by ExileFox** [comment]
> Appimages will not be added

what about flatpak ?
